mysql:
  username: ''
  host: localhost
  enable: true
  password: ''
  database: ''
  port: 3306
  prefix: ''
settings:
  defaultCuboidSize: 11
  logsPerPage: 10
  # 2x the non-logging snitch culling value
  daysFromLastAdminVisitForLoggedSnitchCulling: 28
  daysFromLastAdminVisitForNonLoggedSnitchCulling: 14  
  alertRateLimit: 70
  allowTriggeringLevers: true
  togglerestartgroupcheck: false
  displayOwnerOnSnitchBreak: true
  enableInvisibility: false
  tax_reinforcement_per_alert: false
  max_player_alert_count: 2147483647
#  max_alert_distance:  
#  max_alert_distance_ns:
  softDelete: true
  multipleWorldSupport: false
entryculling:
  enabled: true
  maxcount: 200
  minlifetime: 1
  maxlifetime: 8
snitchculling:
  maxlifetime: 21
  enabled: true
mercury:
  broadcastallservers: false
